all:
  vars:
    ansible_ssh_user: miwwge
  children:
    rpi:
      hosts:
        rpi-01.mellor-house.us:
        rpi-02.mellor-house.us:
        rpi-03.mellor-house.us:
        rpi-04.mellor-house.us:
    ansible:
      hosts:
        ansible.mellor-house.us:
    kubernetes:
      hosts:
        kubernetes-master.mellor-house.us:
      children:
        rpi:
