all:
  vars:
    ansible_ssh_user: miwwge
  children:
    testers:
      hosts:
        test-01.mellor-house.us:
        test-02.mellor-house.us:
        test-03.mellor-house.us:
    rpi:
      hosts:
        rpi-01.mellor-house.us:
        rpi-02.mellor-house.us:
        rpi-03.mellor-house.us:
        rpi-04.mellor-house.us:
    ansible:
      hosts:
        ansible.mellor-house.us:
    kubernetes:
      hosts:
        rancher.mellor-house.us:
      children:
        rpi:
