all:
  children:
    kuberneties:
      hosts:
        # rpi-master.mellor-house.us
        # rpi-worker-1.mellor-house.us
        # rpi-worker-2.mellor-house.us
        # rpi-worker-3.mellor-house.us
        10.1.1.10
        10.1.1.11
        10.1.1.12
        10.1.1.13