---
- hosts: all
  tags: always, update, apt
  become: true
  pre_tasks:
    - name: pre-run | update package index (Debian Based)
      tags: always, update, apt
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

- hosts: all
  tags: always, update, apt
  become: true
  tasks:
    - name: run | update system packages (Debian Based)
      tags: always, update, apt
      apt:
        upgrade: dist
      when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

- hosts: all
  tags: always, update, apt
  become: true
  post_tasks:
    - name: post-run | cleanup package index (Debian Based)
      tags: always, update, apt
      apt:
        autoclean: yes
      changed_when: false
      when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

    - name: post-run | autoremove orphan packages (Debian Based)
      tags: always, update, apt
      apt:
        autoremove: yes
        purge: yes
      changed_when: false
      when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
